# Generated by Django 3.2 on 2022-04-03 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name=datetime.datetime.now)),
                ('created_by', models.CharField(default='system', max_length=15)),
                ('updated_date', models.DateField(verbose_name=datetime.datetime.now)),
                ('updated_by', models.CharField(default='system', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('phone_number', models.PositiveIntegerField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('created_date', models.DateField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=30)),
                ('created_date', models.DateField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.notifications')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.PositiveIntegerField(default='021')),
                ('created_date', models.DateField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.servicetypes')),
            ],
        ),
        migrations.AddField(
            model_name='cameras',
            name='emergency_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Project_XFall.emergencyservices'),
        ),
    ]
