# Generated by Django 3.2 on 2022-05-03 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(default='OFF', max_length=15)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=15)),
                ('updated_date', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('updated_by', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'services_types',
            },
        ),
        migrations.CreateModel(
            name='UserForAdminPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=15)),
                ('free', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('password_confirmation', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'helper',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, upload_to='assets/')),
                ('phone_number', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.roles')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='VerificationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'verification_logs',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'message_recipients',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_status', models.CharField(max_length=10)),
                ('is_logged_out', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='EmergencyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.PositiveIntegerField(default='64')),
                ('created_date', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=15)),
                ('updated_date', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=15)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.servicetypes')),
            ],
            options={
                'db_table': 'emergency_services',
            },
        ),
        migrations.CreateModel(
            name='CamerasUsersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'users_cameras',
            },
        ),
        migrations.AddField(
            model_name='cameras',
            name='emergency_services',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Project_XFall.emergencyservices'),
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.notifications')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
    ]
