# Generated by Django 3.2 on 2022-05-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('verification_code', models.CharField(max_length=255)),
                ('expired_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'user_verification_logs',
            },
        ),
    ]
