# Generated by Django 3.2 on 2022-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
