# Generated by Django 3.2 on 2022-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0003_remove_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, default='021'),
        ),
    ]
