# Generated by Django 3.2 on 2022-04-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0004_users_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='camera',
        ),
        migrations.AlterModelTable(
            name='cameras',
            table='cameras',
        ),
        migrations.AlterModelTable(
            name='emergencyservices',
            table='emergency_services',
        ),
        migrations.AlterModelTable(
            name='notificationhistories',
            table='notification_histories',
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='servicetypes',
            table='services_types',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.CreateModel(
            name='CamerasUsersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.cameras')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_XFall.users')),
            ],
            options={
                'db_table': 'users_cameras',
            },
        ),
    ]
