# Generated by Django 3.2 on 2022-05-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0004_alter_users_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
