# Generated by Django 3.2 on 2022-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0005_auto_20220406_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='status',
            field=models.CharField(default='OFF', max_length=15),
        ),
    ]
