# Generated by Django 3.2 on 2022-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0006_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='scenery',
            field=models.ImageField(blank=True, upload_to='assets/'),
        ),
    ]
