# Generated by Django 3.2 on 2022-04-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0007_auto_20220419_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationhistories',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='notificationhistories',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='updated_date',
        ),
    ]
