# Generated by Django 3.2 on 2022-04-19 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0008_auto_20220419_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistories',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificationhistories',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
