# Generated by Django 3.2 on 2022-05-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_XFall', '0009_alter_notifications_scenery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='scenery',
            new_name='fall_image',
        ),
    ]
